### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by sdxsd** [Abdi-29/push_swap#1]
Please consider licensing this project under the GNU GPLv3. 
At moment your project is proprietary non-free software. 

By licensing under the GNU GPLv3 you're guaranteeing your code as Free Software. By doing that you're protecting against those who may benefit from unclear licensing terms and steal your code for use in proprietary applications that can be used to harm users. 

While you may not think your code is useful to others now, you never know. 

See here for steps to resolve issue: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by Abdi-29** [comment]
thank you sdxsd. i'll add an license as soon as possible
